linter:
  rules:
    erb-no-instance-variables-in-partials:
      enabled: false

    erb-no-unsafe-raw:
      enabled: false

    erb-no-output-in-attribute-name:
      enabled: false

    erb-no-output-in-attribute-position:
      enabled: false

    ujs-no-remote-attribute:
      enabled: false

    ujs-prefer-turbo-confirm:
      enabled: false

    ujs-prefer-turbo-method:
      enabled: false

    ujs-prefer-turbo-submits-with:
      enabled: false

    actionview-prefer-qualified-partial-path:
      enabled: false

framework: actionview
