linter:
  rules:
    erb-no-instance-variables-in-partials:
      enabled: false

    erb-no-unsafe-raw:
      enabled: false

    erb-no-output-in-attribute-name:
      enabled: false

    erb-no-output-in-attribute-position:
      enabled: false
