// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Keyword = 3,
  Action = 4,
  Value = 5,
  Variable = 6,
  String = 7,
  Boolean = 8,
  Number = 9,
  Punctuation = 10
