// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Keyword = 3,
  Variable = 4,
  String = 5,
  Number = 6,
  Boolean = 7,
  Punctuation = 8
