// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQYQPOOOOQO'#Ci'#CiOOQO'#Ce'#CeQYQPOOOOQO-E6c-E6c",
  stateData: "n~O[OSPOS~ORPOSPOTPOUPOVPOWPO~O",
  goto: "i^PPPPPPPPP_PPPeQRORSRTQOR",
  nodeNames: "⚠ LineComment Program Keyword Variable String Number Boolean Punctuation",
  maxTerm: 13,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ".g~ReXY!dYZ!d]^!dpq!drs!uxy#d!P!Q%Z!Q![%l!]!^%t!h!i&P!v!w&t#O#P%a#T#U'Q#V#W'{#W#X(e#X#Y)a#Z#[*U#d#e*t#f#g+d#g#h+v#j#k-q~!iS[~XY!dYZ!d]^!dpq!d~!xTOr!urs#Xs#O!u#O#P#^#P~!u~#^OT~~#aPO~!u~#gP!a!b#j~#mP!^!_#p~#sP!_!`#v~#yP!i!j#|~$PP#`#a$S~$VP#c#d$Y~$]P#U#V$`~$cP#T#U$f~$iP#`#a$l~$oP!O!P$r~$uPyz$x~${P!O!P%O~%RPz{%U~%ZOS~~%^P!P!Q%a~%fQP~OY%aZ~%a~%qPU~!Q![%l~%yQW~OY%tZ~%t~&SP#T#U&V~&YP#`#a&]~&`P#g#h&c~&fP#X#Y&i~&nQV~O!]&i!^~&i~&wP#f#g&z~&}P#i#j&c~'TP#V#W'W~'ZP#h#i'^~'aP#]#^'d~'gP#c#d'j~'mP#b#c'p~'sP#g#h'v~'{OR~~(OP#c#d(R~(UP#b#c(X~([P#W#X(_~(bP#]#^'W~(hP#]#^(k~(nP#g#h(q~(tP#T#U(w~(zP#U#V(}~)QP#`#a)T~)WP#X#Y)Z~)^P#W#X'v~)dP#j#k)g~)jP#X#Y)m~)pP#b#c)s~)vP#h#i)y~*OQR~OY)yZ~)y~*XP#`#a*[~*_P#c#d*b~*eP#U#V*h~*kP#T#U*n~*qP#`#a'v~*wP#`#a*z~*}P#T#U+Q~+TP#m#n+W~+ZP#X#Y+^~+aP#f#g'v~+gP#i#j+j~+mP#`#a+p~+sP#X#Y'v~+yQ#X#Y,P#i#j,o~,SP#h#i,V~,YP#h#i,]~,`P#]#^,c~,fP#b#c,i~,lP#Z#['p~,rP#U#V,u~,xP#f#g,{~-OP#c#d-R~-UP#i#j-X~-[P#h#i-_~-bP#]#^-e~-hP#b#c-k~-nP#X#Y'p~-tP#T#U-w~-zP#f#g-}~.QP#]#^.T~.WP#T#U.Z~.^P#U#V.a~.dP#`#a-k",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
