// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQYQPOOOOQO'#Ci'#CiOOQO'#Ce'#CeQYQPOOOOQO-E6c-E6c",
  stateData: "n~O[OSPOS~ORPOSPOTPOUPOVPOWPO~O",
  goto: "i^PPPPPPPPP_PPPeQRORSRTQOR",
  nodeNames: "⚠ LineComment Program Keyword Variable String Number Boolean Punctuation",
  maxTerm: 13,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ".[~ReXY!dYZ!d]^!dpq!drs!uxy#d!P!Q%Z!Q![%l!]!^%t!h!i&P!v!w&t#O#P%a#T#U'Q#V#W'{#W#X(e#X#Y)a#Z#[)y#d#e*i#f#g+X#g#h+k#j#k-f~!iS[~XY!dYZ!d]^!dpq!d~!xTOr!urs#Xs#O!u#O#P#^#P~!u~#^OT~~#aPO~!u~#gP!a!b#j~#mP!^!_#p~#sP!_!`#v~#yP!i!j#|~$PP#`#a$S~$VP#c#d$Y~$]P#U#V$`~$cP#T#U$f~$iP#`#a$l~$oP!O!P$r~$uPyz$x~${P!O!P%O~%RPz{%U~%ZOS~~%^P!P!Q%a~%fQP~OY%aZ~%a~%qPU~!Q![%l~%yQW~OY%tZ~%t~&SP#T#U&V~&YP#`#a&]~&`P#g#h&c~&fP#X#Y&i~&nQV~O!]&i!^~&i~&wP#f#g&z~&}P#i#j&c~'TP#V#W'W~'ZP#h#i'^~'aP#]#^'d~'gP#c#d'j~'mP#b#c'p~'sP#g#h'v~'{OR~~(OP#c#d(R~(UP#b#c(X~([P#W#X(_~(bP#]#^'W~(hP#]#^(k~(nP#g#h(q~(tP#T#U(w~(zP#U#V(}~)QP#`#a)T~)WP#X#Y)Z~)^P#W#X'v~)dP#j#k)g~)jP#X#Y)m~)pP#b#c)s~)vP#h#i'v~)|P#`#a*P~*SP#c#d*V~*YP#U#V*]~*`P#T#U*c~*fP#`#a'v~*lP#`#a*o~*rP#T#U*u~*xP#m#n*{~+OP#X#Y+R~+UP#f#g'v~+[P#i#j+_~+bP#`#a+e~+hP#X#Y'v~+nQ#X#Y+t#i#j,d~+wP#h#i+z~+}P#h#i,Q~,TP#]#^,W~,ZP#b#c,^~,aP#Z#['p~,gP#U#V,j~,mP#f#g,p~,sP#c#d,v~,yP#i#j,|~-PP#h#i-S~-VP#]#^-Y~-]P#b#c-`~-cP#X#Y'p~-iP#T#U-l~-oP#f#g-r~-uP#]#^-x~-{P#T#U.O~.RP#U#V.U~.XP#`#a-`",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
