-
  name: D.va
  role: Tank
  subrole: Initiator
  stadium: true
-
  name: Domina
  role: Tank
  subrole: Stalwart
  stadium: false
-
  name: Doomfist
  role: Tank
  subrole: Initiator
  stadium: true
-
  name: Hazard
  role: Tank
  subrole: Initiator
  stadium: true
-
  name: Junker Queen
  role: Tank
  subrole: Stalwart
  stadium: true
-
  name: Mauga
  role: Tank
  subrole: Bruiser
  stadium: false
-
  name: Orisa
  role: Tank
  subrole: Bruiser
  stadium: true
-
  name: Ramattra
  role: Tank
  subrole: Stalwart
  stadium: false
-
  name: Reinhardt
  role: Tank
  subrole: Stalwart
  stadium: true
-
  name: Roadhog
  role: Tank
  subrole: Bruiser
  stadium: false
-
  name: Sigma
  role: Tank
  subrole: Stalwart
  stadium: true
-
  name: Winston
  role: Tank
  subrole: Initiator
  stadium: true
-
  name: Wrecking Ball
  role: Tank
  subrole: Initiator
  stadium: false
-
  name: Zarya
  role: Tank
  subrole: Bruiser
  stadium: true
-
  name: Anran
  role: Damage
  subrole: Flanker
  stadium: false
-
  name: Ashe
  role: Damage
  subrole: Sharpshooter
  stadium: true
-
  name: Bastion
  role: Damage
  subrole: Specialist
  stadium: false
-
  name: Cassidy
  role: Damage
  subrole: Sharpshooter
  stadium: true
-
  name: Echo
  role: Damage
  subrole: Recon
  stadium: false
-
  name: Emre
  role: Damage
  subrole: Specialist
  stadium: false
-
  name: Freja
  role: Damage
  subrole: Recon
  stadium: true
-
  name: Genji
  role: Damage
  subrole: Flanker
  stadium: true
-
  name: Hanzo
  role: Damage
  subrole: Sharpshooter
  stadium: false
-
  name: Junkrat
  role: Damage
  subrole: Specialist
  stadium: true
-
  name: Mei
  role: Damage
  subrole: Specialist
  stadium: true
-
  name: Pharah
  role: Damage
  subrole: Recon
  stadium: true
-
  name: Reaper
  role: Damage
  subrole: Flanker
  stadium: true
-
  name: Sojourn
  role: Damage
  subrole: Sharpshooter
  stadium: true
-
  name: "Soldier: 76"
  role: Damage
  subrole: Specialist
  stadium: true
-
  name: Sombra
  role: Damage
  subrole: Recon
  stadium: false
-
  name: Symmetra
  role: Damage
  subrole: Specialist
  stadium: false
-
  name: Torbjörn
  role: Damage
  subrole: Specialist
  stadium: true
-
  name: Tracer
  role: Damage
  subrole: Flanker
  stadium: true
-
  name: Vendetta
  role: Damage
  subrole: Flanker
  stadium: true
-
  name: Venture
  role: Damage
  subrole: Flanker
  stadium: false
-
  name: Widowmaker
  role: Damage
  subrole: Sharpshooter
  stadium: false
-
  name: Ana
  role: Support
  subrole: Tactician
  stadium: true
-
  name: Baptiste
  role: Support
  subrole: Tactician
  stadium: false
-
  name: Brigitte
  role: Support
  subrole: Survivor
  stadium: true
-
  name: Illari
  role: Support
  subrole: Survivor
  stadium: false
-
  name: Jetpack Cat
  role: Support
  subrole: Tactician
  stadium: false
-
  name: Juno
  role: Support
  subrole: Survivor
  stadium: true
-
  name: Kiriko
  role: Support
  subrole: Medic
  stadium: true
-
  name: Lifeweaver
  role: Support
  subrole: Medic
  stadium: false
-
  name: Lúcio
  role: Support
  subrole: Tactician
  stadium: true
-
  name: Mercy
  role: Support
  subrole: Medic
  stadium: true
-
  name: Mizuki
  role: Support
  subrole: Survivor
  stadium: false
-
  name: Moira
  role: Support
  subrole: Medic
  stadium: true
-
  name: Wuyang
  role: Support
  subrole: Survivor
  stadium: true
-
  name: Zenyatta
  role: Support
  subrole: Tactician
  stadium: true
