name: CI
on: [push, pull_request]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  BLIND_INDEX_MASTER_KEY: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
  LOCKBOX_MASTER_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
  DYNOSCALE_URL: ""

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true
      - run: npm install
      - name: ESLint
        run: |
          npx eslint app/javascript
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - run: npm install
      - name: Precompile assets
        run: |
          bundle exec rails vite:build RAILS_ENV=test
      # - name: Test
      #   run: |
      #     bundle exec rake db:test:prepare
      #     bundle exec rails test
      # - name: RSpec
      #   run: |
      #     bundle exec rspec
      - name: Vitest
        run: |
          npm test
  # features:
  #   name: Cucumber Feature Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup System
  #       run: |
  #         sudo apt update
  #         sudo apt-get install libsqlite3-dev
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.2.2
  #         bundler-cache: true
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #         check-latest: true
  #         cache: 'npm'
  #         cache-dependency-path: './package-lock.json'
  #     - run: npm install
  #     - name: Precompile assets
  #       run: |
  #         bundle exec rails vite:build RAILS_ENV=test
  #     - name: Cucumber
  #       run: |
  #         bundle exec rake db:test:prepare
  #         bundle exec cucumber
